### ISSUE TITLE
built error 

### ISSUE THREAD

**Issue by tsingson** [silviucm/pgtogogen#1]
when run "go install github.com/silviucm/pgtogogen"  then a error prompt:

pgtogogen/column.go:24:18: undefined: pgx.NullString

**Comment by silviucm** [comment]
Hi @tsingson ,

Thanks for the issue. This happened yesterday, because I changed the silviucm/pgx fork to point to latest jackc/pgx (v3) so I can do that pull request

Previously, the pgtogogen was working ok with v2 (for generation only, not for runtime), but since yesterday it did not find the v2 references, the old null types like pgx.NullString (which in v3 are replaced with pgtype.Text)

I have committed the changes now by embedding pgx as an internal. Please let me know if it works now. It was my mistake to try and do the pull request from master. I should have created a branch.

1) Remove folder: github.com/silviucm/pgtogogen
2) go get github.com/silviucm/pgtogogen
3) go get github.com/jackc/pgx
4) go install github.com/silviucm/pgtogogen

Cheers
Silviu

**Comment by tsingson** [comment]
@silviucm    thanks. it work!!
